baseURL = 'https://abdelkassar.com/'
languageCode = 'en-us'
title = "Yassin Abdelkassar"

[params]
    author = "Yassin Abdelkassar"
    description = "Computer science and data science student at TU Eindhoven."
    enable_math = true

[params.social]
    github = "yassinkassar"
    linkedin = "yassin-abdelkassar"

[markup.goldmark.renderer]
    unsafe = true
